---
- name: Deploy [ KAFKA ] on destination server.
  hosts: "{{ hosts }}" 
#  connection: local
  serial: 1
  any_errors_fatal: true
  gather_facts: false
#  become: true
#  become_user: kafka
  tasks:
#Creating environment specific deployable unit
    - include: user_creation.yml
    - include: install_kafka_prequisite.yml
    - include: install_kafka.yml
#    - include: openstack_volume-creation.yml 
#    - include: openstack_server-provisioning.yml
#    - include: opendj-install-configure.yml
#    - include: openam-install.yml
